using System.Globalization;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using GrokoShaderGraphPro.Models;
using MediaColor = System.Windows.Media.Color;
using MediaColorConverter = System.Windows.Media.ColorConverter;

namespace GrokoShaderGraphPro.Services;

public sealed partial class ShaderCodeGenerator
{
    private ShaderGraphModel _graph = new();
    private readonly Dictionary<Guid, string> _cache = new();
    private readonly HashSet<Guid> _guard = new();
    private readonly HashSet<string> _features = new(StringComparer.OrdinalIgnoreCase);

    public string GenerateFragmentShader(ShaderGraphModel graph)
    {
        graph.Normalize();
        ShaderGraphSchemaRepair.Repair(graph);
        ShaderGraphDynamicTypes.Synchronize(graph);
        _graph = graph;
        _cache.Clear();
        _guard.Clear();
        _features.Clear();

        var output = graph.Nodes.FirstOrDefault(n => n.Kind == NodeKind.Output);
        var baseColor = BuildOutputInput(output, "Base Color", PinType.Vec3, "vec3(1.0, 0.0, 1.0)");
        var normal = BuildOutputInput(output, "Normal", PinType.Vec3, "normalize(v_NormalWS)");
        var emission = BuildOutputInput(output, "Emission", PinType.Vec3, "vec3(0.0)");
        var alpha = BuildOutputInput(output, "Alpha", PinType.Float, "1.0");
        var alphaClip = BuildOutputInput(output, "Alpha Clip", PinType.Float, "0.0");
        var metallic = BuildOutputInput(output, "Metallic", PinType.Float, "0.0");
        var roughness = BuildOutputRoughnessInput(output);
        var ambientOcclusion = BuildOutputInput(output, "Ambient Occlusion", PinType.Float, "1.0");
        var specular = BuildOutputInput(output, "Specular", PinType.Float, "0.5");
        var clearCoat = BuildOutputInput(output, "Clear Coat", PinType.Float, "0.0");
        var clearCoatRoughness = BuildOutputInput(output, "Clear Coat Roughness", PinType.Float, "0.1");

        var sb = new StringBuilder();
        sb.AppendLine("#version 330 core");
        sb.AppendLine();
        sb.AppendLine("// Generated by Groko Shader Graph Pro GOD MODE");
        sb.AppendLine("// External tool first. Later this file can be integrated into GrokoEngine.");
        sb.AppendLine();
        sb.AppendLine("in vec2 v_UV;");
        sb.AppendLine("in vec3 v_NormalWS;");
        sb.AppendLine("in vec3 v_WorldPos;");
        sb.AppendLine("in vec3 v_ObjectPos;");
        sb.AppendLine("in vec3 v_TangentWS;");
        sb.AppendLine("in vec4 v_ScreenPos;");
        sb.AppendLine("out vec4 FragColor;");
        sb.AppendLine();
        sb.AppendLine("uniform float u_Time;");
        sb.AppendLine("uniform vec2 u_Resolution;");
        sb.AppendLine("uniform vec3 u_CameraPos;");
        sb.AppendLine("uniform vec3 u_LightDir;");
        sb.AppendLine("uniform vec3 u_LightColor;");
        sb.AppendLine("uniform float u_LightIntensity;");
        sb.AppendLine("uniform int u_ColorSpaceLinear;");
        // Sombras direccionales por cascadas (recibidas, igual que el material estándar).
        sb.AppendLine("uniform sampler2DArray u_ShadowMap;");
        sb.AppendLine("uniform int u_ShadowEnabled;");
        sb.AppendLine("uniform float u_ShadowStrength;");
        sb.AppendLine("uniform int u_CascadeCount;");
        sb.AppendLine("uniform mat4 u_CascadeLightMvp[5];");
        sb.AppendLine("uniform float u_CascadeSplit[5];");
        sb.AppendLine("uniform int u_ShadowPcfRadius;");
        sb.AppendLine("uniform float u_ShadowBiasScale;");
        sb.AppendLine("uniform vec3 u_ShadowCameraPos;");
        if (_features.Contains("scenedepth"))
        {
            sb.AppendLine("uniform sampler2D u_SceneDepth;");
            sb.AppendLine("uniform float u_CameraNear;");
            sb.AppendLine("uniform float u_CameraFar;");
        }
        foreach (var uniform in MaterialPropertyUniforms())
            sb.AppendLine(uniform);
        foreach (var sampler in TextureSamplerUniforms())
            sb.AppendLine($"uniform sampler2D {sampler};");
        sb.AppendLine();

        AppendFeatureFunctions(sb);

        sb.AppendLine("void main()");
        sb.AppendLine("{");
        if (_features.Contains("scenedepth"))
            sb.AppendLine("    float v_FragDepth = gl_FragCoord.z;");
        sb.AppendLine($"    vec3 baseColor = {baseColor};");
        sb.AppendLine($"    vec3 normalWS = normalize({normal});");
        sb.AppendLine($"    vec3 emission = {emission};");
        sb.AppendLine($"    float alpha = clamp({alpha}, 0.0, 1.0);");
        sb.AppendLine($"    float alphaClip = {alphaClip};");
        sb.AppendLine($"    float metallic = clamp({metallic}, 0.0, 1.0);");
        sb.AppendLine($"    float roughness = clamp({roughness}, 0.02, 1.0);");
        sb.AppendLine($"    float ambientOcclusion = clamp({ambientOcclusion}, 0.0, 1.0);");
        sb.AppendLine($"    float specular = clamp({specular}, 0.0, 1.0);");
        sb.AppendLine($"    float clearCoat = clamp({clearCoat}, 0.0, 1.0);");
        sb.AppendLine($"    float clearCoatRoughness = clamp({clearCoatRoughness}, 0.02, 1.0);");
        sb.AppendLine("    if (alphaClip > 0.0 && alpha < alphaClip) discard;");
        sb.AppendLine("    // PBR-lite output with main directional light, Schlick Fresnel and GGX-like specular.");
        sb.AppendLine("    vec3 N = normalize(normalWS);");
        sb.AppendLine("    vec3 V = normalize(u_CameraPos - v_WorldPos);");
        sb.AppendLine("    vec3 L = normalize(-u_LightDir);");
        sb.AppendLine("    vec3 H = normalize(V + L);");
        sb.AppendLine("    float NdotL = max(dot(N, L), 0.0);");
        sb.AppendLine("    float NdotV = max(dot(N, V), 0.0);");
        sb.AppendLine("    vec3 F0 = mix(vec3(0.04 + specular * 0.08), baseColor, metallic);");
        sb.AppendLine("    vec3 F = fresnelSchlick(max(dot(H, V), 0.0), F0);");
        sb.AppendLine("    float D = DistributionGGX(N, H, roughness);");
        sb.AppendLine("    float G = GeometrySmith(N, V, L, roughness);");
        sb.AppendLine("    vec3 specularTerm = (D * G * F) / max(4.0 * NdotV * NdotL, 0.0001);");
        sb.AppendLine("    vec3 kS = F;");
        sb.AppendLine("    vec3 kD = (vec3(1.0) - kS) * (1.0 - metallic);");
        sb.AppendLine("    vec3 diffuseColor = baseColor * (1.0 - metallic);");
        sb.AppendLine("    vec3 ambient = diffuseColor * ambientOcclusion * (0.18 + 0.22 * clamp(N.y * 0.5 + 0.5, 0.0, 1.0));");
        sb.AppendLine("    vec3 radiance = u_LightColor * u_LightIntensity;");
        sb.AppendLine("    float shadowReceive = ReceiveShadow(N, u_LightDir);");
        sb.AppendLine("    vec3 direct = (kD * diffuseColor / 3.14159265 + specularTerm) * NdotL * radiance * shadowReceive;");
        sb.AppendLine("    float rim = pow(1.0 - max(dot(N, V), 0.0), mix(8.0, 2.0, clearCoatRoughness)) * clearCoat;");
        sb.AppendLine("    vec3 finalColor = clamp(ambient + direct + vec3(rim * 0.18) + emission, vec3(0.0), vec3(64.0));");
        sb.AppendLine("    FragColor = vec4(finalColor, alpha);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public string GenerateNodePreviewFragmentShader(ShaderGraphModel graph, Guid nodeId, Guid? outputPinId = null)
    {
        graph.Normalize();
        ShaderGraphSchemaRepair.Repair(graph);
        ShaderGraphDynamicTypes.Synchronize(graph);
        _graph = graph;
        _cache.Clear();
        _guard.Clear();
        _features.Clear();

        var node = graph.Nodes.FirstOrDefault(n => n.Id == nodeId);
        var outputPin = outputPinId.HasValue
            ? node?.Outputs.FirstOrDefault(p => p.Id == outputPinId.Value)
            : node?.Outputs.FirstOrDefault();

        var type = outputPin is null || node is null ? PinType.Float : ResolveOutputType(node, outputPin);
        var expr = outputPin is null || node is null ? DefaultForType(type) : BuildOutput(node, outputPin);
        var preview = PreviewColorExpression(expr, type);

        var sb = new StringBuilder();
        sb.AppendLine("#version 330 core");
        sb.AppendLine();
        sb.AppendLine("in vec2 v_UV;");
        sb.AppendLine("in vec3 v_NormalWS;");
        sb.AppendLine("in vec3 v_WorldPos;");
        sb.AppendLine("in vec3 v_ObjectPos;");
        sb.AppendLine("in vec3 v_TangentWS;");
        sb.AppendLine("in vec4 v_ScreenPos;");
        sb.AppendLine("out vec4 FragColor;");
        sb.AppendLine();
        sb.AppendLine("uniform float u_Time;");
        sb.AppendLine("uniform vec2 u_Resolution;");
        sb.AppendLine("uniform vec3 u_CameraPos;");
        sb.AppendLine("uniform vec3 u_LightDir;");
        sb.AppendLine("uniform vec3 u_LightColor;");
        sb.AppendLine("uniform float u_LightIntensity;");
        sb.AppendLine("uniform int u_ColorSpaceLinear;");
        // Sombras direccionales por cascadas (recibidas, igual que el material estándar).
        sb.AppendLine("uniform sampler2DArray u_ShadowMap;");
        sb.AppendLine("uniform int u_ShadowEnabled;");
        sb.AppendLine("uniform float u_ShadowStrength;");
        sb.AppendLine("uniform int u_CascadeCount;");
        sb.AppendLine("uniform mat4 u_CascadeLightMvp[5];");
        sb.AppendLine("uniform float u_CascadeSplit[5];");
        sb.AppendLine("uniform int u_ShadowPcfRadius;");
        sb.AppendLine("uniform float u_ShadowBiasScale;");
        sb.AppendLine("uniform vec3 u_ShadowCameraPos;");
        if (_features.Contains("scenedepth"))
        {
            sb.AppendLine("uniform sampler2D u_SceneDepth;");
            sb.AppendLine("uniform float u_CameraNear;");
            sb.AppendLine("uniform float u_CameraFar;");
        }
        foreach (var uniform in MaterialPropertyUniforms())
            sb.AppendLine(uniform);
        foreach (var sampler in TextureSamplerUniforms())
            sb.AppendLine($"uniform sampler2D {sampler};");
        sb.AppendLine();

        AppendFeatureFunctions(sb);

        sb.AppendLine("void main()");
        sb.AppendLine("{");
        if (_features.Contains("scenedepth"))
            sb.AppendLine("    float v_FragDepth = gl_FragCoord.z;");
        sb.AppendLine($"    vec3 previewColor = clamp({preview}, vec3(0.0), vec3(1.0));");
        sb.AppendLine("    FragColor = vec4(previewColor, 1.0);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string PreviewColorExpression(string expr, PinType type)
    {
        return type switch
        {
            PinType.Float => $"vec3({expr})",
            PinType.Vec2 => $"vec3(({expr}).xy, 0.0)",
            PinType.Vec3 => expr,
            PinType.Vec4 => $"({expr}).rgb",
            _ => "vec3(0.0)"
        };
    }

    public string GenerateVertexShader()
    {
        return """
#version 330 core

// Generated by Groko Shader Graph Pro - vertex shader base.
layout(location = 0) in vec3 a_Position;
layout(location = 1) in vec3 a_Normal;
layout(location = 2) in vec2 a_UV;

uniform mat4 u_Model;
uniform mat4 u_View;
uniform mat4 u_Projection;

out vec2 v_UV;
out vec3 v_NormalWS;
out vec3 v_WorldPos;
out vec3 v_ObjectPos;
out vec3 v_TangentWS;
out vec4 v_ScreenPos;

void main()
{
    vec4 world = u_Model * vec4(a_Position, 1.0);
    v_WorldPos = world.xyz;
    v_ObjectPos = a_Position;
    v_NormalWS = normalize(mat3(u_Model) * a_Normal);
    vec3 tangentOS = abs(a_Normal.y) > 0.99 ? vec3(1.0, 0.0, 0.0) : normalize(cross(vec3(0.0, 1.0, 0.0), a_Normal));
    v_TangentWS = normalize(mat3(u_Model) * tangentOS);
    v_UV = a_UV;
    gl_Position = u_Projection * u_View * world;
    v_ScreenPos = gl_Position;
}
""";
    }

    public string GenerateHlslFragmentShader(ShaderGraphModel graph)
    {
        graph.Normalize();
        ShaderGraphSchemaRepair.Repair(graph);
        ShaderGraphDynamicTypes.Synchronize(graph);
        _graph = graph;
        _cache.Clear();
        _guard.Clear();
        _features.Clear();

        var output = graph.Nodes.FirstOrDefault(n => n.Kind == NodeKind.Output);
        var baseColor = ToHlslExpression(BuildOutputInput(output, "Base Color", PinType.Vec3, "vec3(1.0, 0.0, 1.0)"));
        var normal = ToHlslExpression(BuildOutputInput(output, "Normal", PinType.Vec3, "normalize(v_NormalWS)"));
        var emission = ToHlslExpression(BuildOutputInput(output, "Emission", PinType.Vec3, "vec3(0.0)"));
        var alpha = ToHlslExpression(BuildOutputInput(output, "Alpha", PinType.Float, "1.0"));
        var alphaClip = ToHlslExpression(BuildOutputInput(output, "Alpha Clip", PinType.Float, "0.0"));
        var metallic = ToHlslExpression(BuildOutputInput(output, "Metallic", PinType.Float, "0.0"));
        var roughness = ToHlslExpression(BuildOutputRoughnessInput(output));
        var ambientOcclusion = ToHlslExpression(BuildOutputInput(output, "Ambient Occlusion", PinType.Float, "1.0"));
        var specular = ToHlslExpression(BuildOutputInput(output, "Specular", PinType.Float, "0.5"));
        var clearCoat = ToHlslExpression(BuildOutputInput(output, "Clear Coat", PinType.Float, "0.0"));
        var clearCoatRoughness = ToHlslExpression(BuildOutputInput(output, "Clear Coat Roughness", PinType.Float, "0.1"));

        var sb = new StringBuilder();
        sb.AppendLine("// HLSL generated by Groko Shader Graph Pro GOD MODE");
        sb.AppendLine("// Pixel shader real, not a GLSL comment dump.");
        sb.AppendLine();
        sb.AppendLine("cbuffer GrokoMaterial : register(b0)");
        sb.AppendLine("{");
        sb.AppendLine("    float u_Time;");
        sb.AppendLine("    float2 u_Resolution;");
        sb.AppendLine("    float3 u_CameraPos;");
        sb.AppendLine("    float _GrokoPadding0;");
        sb.AppendLine("    float3 u_LightDir;");
        sb.AppendLine("    float _GrokoPadding1;");
        if (_features.Contains("scenedepth"))
        {
            sb.AppendLine("    float u_CameraNear;");
            sb.AppendLine("    float u_CameraFar;");
            sb.AppendLine("    float2 _GrokoPadding2;");
        }
        foreach (var uniform in MaterialPropertyUniforms())
            sb.AppendLine("    " + ToHlslUniformField(uniform));
        sb.AppendLine("};");
        sb.AppendLine();

        var slot = 0;
        foreach (var sampler in TextureSamplerUniforms())
        {
            sb.AppendLine($"Texture2D {sampler} : register(t{slot});");
            slot++;
        }
        if (_features.Contains("scenedepth"))
            sb.AppendLine($"Texture2D u_SceneDepth : register(t{slot});");
        sb.AppendLine("SamplerState GrokoLinearSampler : register(s0);");
        sb.AppendLine();
        sb.AppendLine("cbuffer GrokoObject : register(b1)");
        sb.AppendLine("{");
        sb.AppendLine("    float4x4 u_Model;");
        sb.AppendLine("    float4x4 u_View;");
        sb.AppendLine("    float4x4 u_Projection;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("struct VSInput");
        sb.AppendLine("{");
        sb.AppendLine("    float3 PositionOS : POSITION;");
        sb.AppendLine("    float3 NormalOS : NORMAL;");
        sb.AppendLine("    float2 UV : TEXCOORD0;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("struct PSInput");
        sb.AppendLine("{");
        sb.AppendLine("    float4 PositionCS : SV_POSITION;");
        sb.AppendLine("    float2 v_UV : TEXCOORD0;");
        sb.AppendLine("    float3 v_NormalWS : TEXCOORD1;");
        sb.AppendLine("    float3 v_WorldPos : TEXCOORD2;");
        sb.AppendLine("    float3 v_ObjectPos : TEXCOORD3;");
        sb.AppendLine("    float3 v_TangentWS : TEXCOORD4;");
        sb.AppendLine("    float4 v_ScreenPos : TEXCOORD5;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("PSInput VSMain(VSInput input)");
        sb.AppendLine("{");
        sb.AppendLine("    PSInput o;");
        sb.AppendLine("    float4 world = mul(float4(input.PositionOS, 1.0), u_Model);");
        sb.AppendLine("    o.v_WorldPos = world.xyz;");
        sb.AppendLine("    o.v_ObjectPos = input.PositionOS;");
        sb.AppendLine("    o.v_NormalWS = normalize(mul(float4(input.NormalOS, 0.0), u_Model).xyz);");
        sb.AppendLine("    o.v_TangentWS = normalize(mul(float4(1.0, 0.0, 0.0, 0.0), u_Model).xyz);");
        sb.AppendLine("    o.v_UV = input.UV;");
        sb.AppendLine("    o.PositionCS = mul(mul(world, u_View), u_Projection);");
        sb.AppendLine("    o.v_ScreenPos = o.PositionCS;");
        sb.AppendLine("    return o;");
        sb.AppendLine("}");
        sb.AppendLine();
        AppendHlslFeatureFunctions(sb);
        sb.AppendLine("float4 PSMain(PSInput input) : SV_Target");
        sb.AppendLine("{");
        sb.AppendLine("    float2 v_UV = input.v_UV;");
        sb.AppendLine("    float3 v_NormalWS = input.v_NormalWS;");
        sb.AppendLine("    float3 v_WorldPos = input.v_WorldPos;");
        sb.AppendLine("    float3 v_ObjectPos = input.v_ObjectPos;");
        sb.AppendLine("    float3 v_TangentWS = input.v_TangentWS;");
        sb.AppendLine("    float4 v_ScreenPos = input.v_ScreenPos;");
        if (_features.Contains("scenedepth"))
            sb.AppendLine("    float v_FragDepth = input.PositionCS.z;");
        sb.AppendLine($"    float3 baseColor = {baseColor};");
        sb.AppendLine($"    float3 normalWS = normalize({normal});");
        sb.AppendLine($"    float3 emission = {emission};");
        sb.AppendLine($"    float alpha = saturate({alpha});");
        sb.AppendLine($"    float alphaClip = {alphaClip};");
        sb.AppendLine($"    float metallic = saturate({metallic});");
        sb.AppendLine($"    float roughness = clamp({roughness}, 0.02, 1.0);");
        sb.AppendLine($"    float ambientOcclusion = saturate({ambientOcclusion});");
        sb.AppendLine($"    float specular = saturate({specular});");
        sb.AppendLine($"    float clearCoat = saturate({clearCoat});");
        sb.AppendLine($"    float clearCoatRoughness = clamp({clearCoatRoughness}, 0.02, 1.0);");
        sb.AppendLine("    if (alphaClip > 0.0 && alpha < alphaClip) discard;");
        sb.AppendLine("    float3 N = normalize(normalWS);");
        sb.AppendLine("    float3 V = normalize(u_CameraPos - v_WorldPos);");
        sb.AppendLine("    float3 L = normalize(-u_LightDir);");
        sb.AppendLine("    float3 H = normalize(V + L);");
        sb.AppendLine("    float NdotL = saturate(dot(N, L));");
        sb.AppendLine("    float NdotV = saturate(dot(N, V));");
        sb.AppendLine("    float3 F0 = lerp(float3(0.04 + specular * 0.08, 0.04 + specular * 0.08, 0.04 + specular * 0.08), baseColor, metallic);");
        sb.AppendLine("    float3 F = fresnelSchlick(max(dot(H, V), 0.0), F0);");
        sb.AppendLine("    float D = DistributionGGX(N, H, roughness);");
        sb.AppendLine("    float G = GeometrySmith(N, V, L, roughness);");
        sb.AppendLine("    float3 specTerm = (D * G * F) / max(4.0 * NdotV * NdotL, 0.0001);");
        sb.AppendLine("    float3 kS = F;");
        sb.AppendLine("    float3 kD = (1.0 - kS) * (1.0 - metallic);");
        sb.AppendLine("    float3 diffuse = baseColor * (1.0 - metallic);");
        sb.AppendLine("    float3 ambient = diffuse * ambientOcclusion * (0.18 + 0.22 * saturate(N.y * 0.5 + 0.5));");
        sb.AppendLine("    float rim = pow(1.0 - saturate(dot(N, V)), lerp(8.0, 2.0, clearCoatRoughness)) * clearCoat;");
        sb.AppendLine("    float3 finalColor = clamp(ambient + (kD * diffuse / 3.14159265 + specTerm) * NdotL + float3(rim * 0.18, rim * 0.18, rim * 0.18) + emission, float3(0.0, 0.0, 0.0), float3(64.0, 64.0, 64.0));");
        sb.AppendLine("    return float4(finalColor, alpha);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private string BuildOutputInput(ShaderNode? output, string pinName, PinType type, string fallback)
    {
        var pin = output?.Input(pinName);
        if (pin is null && pinName.Equals("Base Color", StringComparison.OrdinalIgnoreCase))
            pin = output?.Input("Color"); // legacy graph compatibility

        if (pin is null)
            return fallback;

        // Los graphs viejos guardaban el Normal del Master como vec3(0,0,1),
        // lo que hacía que Sphere/Cube/Plane se vieran planos en OpenGL.
        // Si no hay cable conectado al Normal, usamos la normal real de la malla.
        if (pinName.Equals("Normal", StringComparison.OrdinalIgnoreCase)
            && _graph.FindConnectionToInput(pin.Id) is null)
        {
            return fallback;
        }

        return BuildInput(pin, type);
    }

    private string BuildOutputRoughnessInput(ShaderNode? output)
    {
        var smoothness = output?.Input("Smoothness");
        if (smoothness is not null && _graph.FindConnectionToInput(smoothness.Id) is not null)
            return $"(1.0 - clamp({BuildInput(smoothness, PinType.Float)}, 0.0, 1.0))";

        return BuildOutputInput(output, "Roughness", PinType.Float, "0.5");
    }

    private string BuildInput(GraphPin? inputPin, PinType expectedType)
    {
        if (inputPin is null)
            return DefaultForType(expectedType);

        var connection = _graph.FindConnectionToInput(inputPin.Id);
        if (connection is null)
            return CastExpression(inputPin.DefaultValue, inputPin.Type, expectedType);

        var sourcePin = _graph.FindPin(connection.FromPinId);
        var sourceNode = _graph.FindNodeByPin(connection.FromPinId);
        if (sourcePin is null || sourceNode is null)
            return CastExpression(inputPin.DefaultValue, inputPin.Type, expectedType);

        return CastExpression(BuildOutput(sourceNode, sourcePin), ResolveOutputType(sourceNode, sourcePin), expectedType);
    }

    private static GraphPin? InputAny(ShaderNode node, params string[] names)
    {
        foreach (var name in names)
        {
            var pin = node.Input(name);
            if (pin is not null)
                return pin;
        }

        return null;
    }

    private bool IsInputConnectedFrom(GraphPin? inputPin, NodeKind kind)
    {
        if (inputPin is null)
            return false;

        var connection = _graph.FindConnectionToInput(inputPin.Id);
        return connection is not null
            && _graph.FindNodeByPin(connection.FromPinId)?.Kind == kind;
    }

    private string BuildOutput(ShaderNode node, GraphPin outputPin)
    {
        if (_cache.TryGetValue(outputPin.Id, out var cached))
            return cached;

        if (!_guard.Add(outputPin.Id))
            return DefaultForType(outputPin.Type);

        string expression = node.Kind switch
        {
            NodeKind.ConstantFloat => F(node.FloatValue),
            NodeKind.ConstantColor => ToVec3(node.ColorHex, node.ColorIntensity),
            NodeKind.ConstantVector2 => ToVec2(node.TextValue),
            NodeKind.ConstantVector3 => ToVec3FromText(node.TextValue),
            NodeKind.Time => BuildTime(outputPin),
            NodeKind.TextureCoord => "v_UV",
            NodeKind.TangentVector => "normalize(v_TangentWS)",
            NodeKind.CameraVector => "normalize(u_CameraPos - v_WorldPos)",
            NodeKind.ObjectPosition => "v_ObjectPos",
            NodeKind.ScreenPosition => BuildScreenPosition(node, outputPin),
            NodeKind.PropertyFloat => SanitizeIdentifier(PropertyUniformName(node)),
            NodeKind.PropertyColor => BuildPropertyColorOutput(node),
            NodeKind.PropertyVector2 => SanitizeIdentifier(PropertyUniformName(node)),
            NodeKind.PropertyVector3 => SanitizeIdentifier(PropertyUniformName(node)),
            NodeKind.PropertyVector4 => SanitizeIdentifier(PropertyUniformName(node)),
            NodeKind.PropertyTexture2D => SanitizeIdentifier(PropertyUniformName(node)),
            NodeKind.TextureSample => BuildTextureSample(node, outputPin),
            NodeKind.Flipbook => BuildFlipbook(node),
            NodeKind.NormalVector => "normalize(v_NormalWS)",
            NodeKind.ViewDirection => "normalize(u_CameraPos - v_WorldPos)",
            NodeKind.WorldPosition => "v_WorldPos",
            NodeKind.Add => BuildBinaryAuto(node, outputPin, "+"),
            NodeKind.Subtract => BuildBinaryAuto(node, outputPin, "-"),
            NodeKind.Multiply => BuildBinaryAuto(node, outputPin, "*"),
            NodeKind.Divide => BuildDivide(node, outputPin),
            NodeKind.Power => BuildPower(node),
            NodeKind.Sin => BuildUnaryAuto(node, "sin"),
            NodeKind.Cos => BuildUnaryAuto(node, "cos"),
            NodeKind.Clamp => BuildClamp(node),
            NodeKind.Smoothstep => BuildSmoothstep(node),
            NodeKind.Remap => BuildRemap(node),
            NodeKind.OneMinus => BuildOneMinus(node),
            NodeKind.Posterize => BuildPosterize(node),
            NodeKind.Length => BuildLength(node),
            NodeKind.Saturate => BuildSaturate(node),
            NodeKind.Step => BuildStep(node),
            NodeKind.Abs => BuildUnaryAuto(node, "abs"),
            NodeKind.Floor => BuildUnaryAuto(node, "floor"),
            NodeKind.Ceil => BuildUnaryAuto(node, "ceil"),
            NodeKind.Fraction => BuildUnaryAuto(node, "fract"),
            NodeKind.Min => BuildMinMax(node, outputPin, "min"),
            NodeKind.Max => BuildMinMax(node, outputPin, "max"),
            NodeKind.Lerp => BuildLerp(node, outputPin),
            NodeKind.Negate => BuildNegate(node),
            NodeKind.Reciprocal => BuildReciprocal(node),
            NodeKind.MultiplyAdd => BuildMultiplyAdd(node),
            NodeKind.Normalize => BuildNormalize(node),
            NodeKind.Dot => BuildDot(node),
            NodeKind.Cross => $"cross({BuildInput(node.Input("A")!, PinType.Vec3)}, {BuildInput(node.Input("B")!, PinType.Vec3)})",
            NodeKind.Noise => BuildNoise(node),
            NodeKind.GradientNoise => BuildGradientNoise(node),
            NodeKind.Checkerboard => BuildCheckerboard(node),
            NodeKind.Voronoi => BuildVoronoi(node, outputPin),
            NodeKind.SceneDepth => BuildSceneDepth(node, outputPin),
            NodeKind.DepthFade => BuildDepthFade(node),
            NodeKind.Triplanar => BuildTriplanar(node, outputPin),
            NodeKind.Fresnel => BuildFresnel(node),
            NodeKind.FresnelPro => BuildFresnelPro(node),
            NodeKind.RimLight => BuildRimLight(node, outputPin),
            NodeKind.EmissionPulse => BuildEmissionPulse(node, outputPin),
            NodeKind.Dissolve => BuildDissolve(node, outputPin),
            NodeKind.Gradient => BuildGradient(node),
            NodeKind.Twirl => BuildTwirl(node),
            NodeKind.NormalMap => BuildNormalMap(node),
            NodeKind.NormalBlend => BuildNormalBlend(node),
            NodeKind.NormalStrength => BuildNormalStrength(node),
            NodeKind.MetallicMap => BuildScalarTextureMap(node),
            NodeKind.SmoothnessMap => BuildScalarTextureMap(node),
            NodeKind.AmbientOcclusionMap => BuildScalarTextureMap(node),
            NodeKind.ChannelSplit or NodeKind.Split => BuildChannelSplit(node, outputPin),
            NodeKind.ChannelCombine or NodeKind.Combine => BuildChannelCombine(node, outputPin),
            NodeKind.Swizzle => BuildSwizzle(node, outputPin),
            NodeKind.Append => BuildAppend(node, outputPin),
            NodeKind.ChannelMask => BuildChannelMask(node),
            NodeKind.InvertColor => $"(vec3(1.0) - {BuildInput(node.Input("In")!, PinType.Vec3)})",
            NodeKind.BrightnessContrast => BuildBrightnessContrast(node),
            NodeKind.ColorRamp => BuildColorRamp(node),
            NodeKind.PolarCoordinates => BuildPolarCoordinates(node),
            NodeKind.RadialGradient => BuildRadialGradient(node),
            NodeKind.Distance => BuildDistance(node),
            NodeKind.SphereMask => BuildSphereMask(node),
            NodeKind.Blend => BuildBlend(node),
            NodeKind.UVScroll or NodeKind.Panner => BuildPanner(node),
            NodeKind.TilingOffset => BuildTilingOffset(node),
            NodeKind.Rotator => BuildRotator(node),
            NodeKind.ParallaxOffset => BuildParallaxOffset(node),
            NodeKind.Mix => BuildMix(node),
            NodeKind.SubGraph => BuildSubGraph(node, outputPin),
            _ => DefaultForType(outputPin.Type)
        };

        _guard.Remove(outputPin.Id);
        _cache[outputPin.Id] = expression;
        return expression;
    }

    private string BuildTextureSample(ShaderNode node, GraphPin outputPin)
    {
        var texturePin = node.Input("Texture");
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var tilingPin = node.Input("Tiling");
        var offsetPin = node.Input("Offset");
        var tiling = tilingPin is null ? "vec2(1.0, 1.0)" : BuildInput(tilingPin, PinType.Vec2);
        var offset = offsetPin is null ? "vec2(0.0, 0.0)" : BuildInput(offsetPin, PinType.Vec2);
        var sampleUv = $"(({uv}) * {tiling} + {offset})";
        var samplerName = texturePin is null ? SanitizeIdentifier(TextureUniformName(node)) : BuildInput(texturePin, PinType.Texture2D);
        samplerName = SanitizeIdentifier(samplerName);
        var sample = $"texture({samplerName}, {sampleUv})";
        var rgb = $"{sample}.rgb";
        // Las texturas de color (albedo) vienen codificadas en sRGB; se decodifican a
        // lineal igual que en el shader de objetos sólidos para que se vean iguales.
        var linearRgb = node.TextureSettings.SRgb && !node.TextureSettings.IsNormalMap
            ? $"(u_ColorSpaceLinear == 1 ? pow({rgb}, vec3(2.2)) : {rgb})"
            : rgb;
        var outputRgb = node.TextureSettings.IsNormalMap
            ? $"normalize(({rgb}) * 2.0 - 1.0)"
            : linearRgb;

        return outputPin.Name.ToLowerInvariant() switch
        {
            "rgba" => $"vec4({outputRgb}, {sample}.a)",
            "rgb" => outputRgb,
            "r" => $"{sample}.r",
            "g" => $"{sample}.g",
            "b" => $"{sample}.b",
            "a" or "alpha" => $"{sample}.a",
            _ => $"{sample}.rgb"
        };
    }

    private string BuildScreenPosition(ShaderNode node, GraphPin outputPin)
    {
        var uv = "((v_ScreenPos.xy / max(v_ScreenPos.w, 0.00001)) * 0.5 + 0.5)";
        string RawScreenPosition()
        {
            _features.Add("scenedepth");
            return "vec4(v_ScreenPos.xy, v_ScreenPos.z, sceneDepthLinearEye(v_FragDepth))";
        }

        if (outputPin.Name.Equals("UV", StringComparison.OrdinalIgnoreCase))
            return uv;
        if (outputPin.Name.Equals("Raw", StringComparison.OrdinalIgnoreCase))
            return RawScreenPosition();

        var mode = string.IsNullOrWhiteSpace(node.TextValue) ? "Raw" : node.TextValue.Trim();
        return mode.ToLowerInvariant() switch
        {
            "raw" => RawScreenPosition(),
            "center" => $"vec4(({uv}) * 2.0 - 1.0, 0.0, 1.0)",
            "tiled" => $"vec4(fract({uv}), 0.0, 1.0)",
            "pixel" => "vec4(v_ScreenPos.xy, v_ScreenPos.zw)",
            _ => $"vec4({uv}, 0.0, 1.0)"
        };
    }

    private string BuildFlipbook(ShaderNode node)
    {
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var columns = BuildInput(node.Input("Columns")!, PinType.Float);
        var rows = BuildInput(node.Input("Rows")!, PinType.Float);
        var frame = BuildInput(node.Input("Frame")!, PinType.Float);
        return $"flipbookUV({uv}, max({columns}, 1.0), max({rows}, 1.0), {frame})";
    }

    private string BuildPropertyColorOutput(ShaderNode node)
    {
        var name = SanitizeIdentifier(PropertyUniformName(node));
        var blackboardProp = (_graph.Properties ?? new List<GraphProperty>())
            .FirstOrDefault(p => SanitizeIdentifier(p.UniformName).Equals(name, StringComparison.OrdinalIgnoreCase));
        return blackboardProp is { Type: PinType.Vec4 } ? $"{name}.rgb" : name;
    }

    private static string BuildTime(GraphPin outputPin)
    {
        return outputPin.Name.ToLowerInvariant() switch
        {
            "sine time" => "sin(u_Time)",
            "cosine time" => "cos(u_Time)",
            "delta time" => "0.0166667",
            "smooth delta" => "0.0166667",
            _ => "u_Time"
        };
    }

    private static string PropertyUniformName(ShaderNode node)
    {
        var value = string.IsNullOrWhiteSpace(node.TextValue) ? node.Title : node.TextValue.Trim();
        return value.StartsWith("u_", StringComparison.OrdinalIgnoreCase) ? value : "u_" + value;
    }

    private static string TextureUniformName(ShaderNode node)
    {
        var value = string.IsNullOrWhiteSpace(node.TextValue) ? string.Empty : node.TextValue.Trim();
        if (!string.IsNullOrWhiteSpace(node.TexturePath) && IsDefaultTextureUniformName(value))
            return LocalTextureUniformName(node);

        if (string.IsNullOrWhiteSpace(value))
            value = "u_MainTex";

        var fileName = Path.GetFileNameWithoutExtension(value);
        if (!string.IsNullOrWhiteSpace(fileName) && (value.Contains('\\') || value.Contains('/') || value.Contains('.')))
            return "u_" + fileName;
        return value;
    }

    private static bool IsDefaultTextureUniformName(string? value)
    {
        var v = (value ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(v))
            return true;

        return v.Equals("MainTex", StringComparison.OrdinalIgnoreCase)
            || v.Equals("u_MainTex", StringComparison.OrdinalIgnoreCase)
            || v.Equals("NormalMap", StringComparison.OrdinalIgnoreCase)
            || v.Equals("u_NormalMap", StringComparison.OrdinalIgnoreCase)
            || v.Equals("MetallicMap", StringComparison.OrdinalIgnoreCase)
            || v.Equals("u_MetallicMap", StringComparison.OrdinalIgnoreCase)
            || v.Equals("SmoothnessMap", StringComparison.OrdinalIgnoreCase)
            || v.Equals("u_SmoothnessMap", StringComparison.OrdinalIgnoreCase)
            || v.Equals("AOMap", StringComparison.OrdinalIgnoreCase)
            || v.Equals("u_AOMap", StringComparison.OrdinalIgnoreCase);
    }

    private static string LocalTextureUniformName(ShaderNode node)
    {
        var prefix = node.Kind switch
        {
            NodeKind.NormalMap => "u_NormalMap_",
            NodeKind.MetallicMap => "u_MetallicMap_",
            NodeKind.SmoothnessMap => "u_SmoothnessMap_",
            NodeKind.AmbientOcclusionMap => "u_AOMap_",
            NodeKind.Triplanar => "u_Triplanar_",
            _ => "u_Texture_"
        };

        return prefix + node.Id.ToString("N")[..8];
    }

    private IEnumerable<string> TextureSamplerUniforms()
    {
        var direct = _graph.Nodes
            .Where(n => n.Kind == NodeKind.TextureSample || n.Kind == NodeKind.NormalMap || n.Kind == NodeKind.Triplanar
                        || n.Kind == NodeKind.MetallicMap || n.Kind == NodeKind.SmoothnessMap || n.Kind == NodeKind.AmbientOcclusionMap)
            .Select(n => SanitizeIdentifier(TextureUniformName(n)));

        var nodeProperties = _graph.Nodes
            .Where(n => n.Kind == NodeKind.PropertyTexture2D)
            .Select(n => SanitizeIdentifier(PropertyUniformName(n)));

        var blackboardProperties = (_graph.Properties ?? new List<GraphProperty>())
            .Where(p => p.Type == PinType.Texture2D)
            .Select(p => SanitizeIdentifier(p.UniformName));

        return direct.Concat(nodeProperties).Concat(blackboardProperties).Distinct(StringComparer.OrdinalIgnoreCase);
    }

    private IEnumerable<string> MaterialPropertyUniforms()
    {
        var uniforms = new List<string>();
        var declared = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        // Los samplers (Texture2D) ya ocupan estos nombres; un uniform numérico con el
        // mismo nombre produciría una redeclaración inválida en GLSL/HLSL.
        var textureNames = new HashSet<string>(TextureSamplerUniforms(), StringComparer.OrdinalIgnoreCase);
        foreach (var name in textureNames)
            declared.Add(name);

        // Las propiedades del Blackboard tienen prioridad: si un nodo Property* del
        // canvas referencia el mismo nombre, no debe redeclarar el uniform con otro tipo.
        foreach (var property in _graph.Properties ?? new List<GraphProperty>())
        {
            var name = SanitizeIdentifier(property.UniformName);
            if (!declared.Add(name)) continue;
            switch (property.Type)
            {
                case PinType.Float:
                    uniforms.Add($"uniform float {name};");
                    break;
                case PinType.Vec2:
                    uniforms.Add($"uniform vec2 {name};");
                    break;
                case PinType.Vec3:
                    uniforms.Add($"uniform vec3 {name};");
                    break;
                case PinType.Vec4:
                    uniforms.Add($"uniform vec4 {name};");
                    break;
            }
        }

        foreach (var node in _graph.Nodes)
        {
            var name = SanitizeIdentifier(PropertyUniformName(node));
            if (!declared.Add(name)) continue;
            switch (node.Kind)
            {
                case NodeKind.PropertyFloat:
                    uniforms.Add($"uniform float {name};");
                    break;
                case NodeKind.PropertyColor:
                case NodeKind.PropertyVector3:
                    uniforms.Add($"uniform vec3 {name};");
                    break;
                case NodeKind.PropertyVector4:
                    uniforms.Add($"uniform vec4 {name};");
                    break;
                case NodeKind.PropertyVector2:
                    uniforms.Add($"uniform vec2 {name};");
                    break;
            }
        }

        return uniforms;
    }

    private static string SanitizeIdentifier(string value)
    {
        var chars = value.Select((c, i) => (char.IsLetter(c) || c == '_' || (i > 0 && char.IsDigit(c))) ? c : '_').ToArray();
        var result = new string(chars);
        return string.IsNullOrWhiteSpace(result) ? "u_MainTex" : result;
    }

    private string BuildBinaryAuto(ShaderNode node, GraphPin outputPin, string op)
    {
        var aPin = node.Input("A")!;
        var bPin = node.Input("B")!;
        var type = HighestNumericType(ResolveInputType(aPin), ResolveInputType(bPin), outputPin.Type);
        var a = BuildInput(aPin, type);
        var b = BuildInput(bPin, type);
        return $"({a} {op} {b})";
    }

    private string BuildDivide(ShaderNode node, GraphPin outputPin)
    {
        var aPin = node.Input("A")!;
        var bPin = node.Input("B")!;
        var type = HighestNumericType(ResolveInputType(aPin), ResolveInputType(bPin), outputPin.Type);
        var a = BuildInput(aPin, type);
        var b = BuildInput(bPin, type);
        var safeB = type == PinType.Float
            ? $"max(abs({b}), 0.00001)"
            : $"max(abs({b}), {ConstructorForType(type, "0.00001")})";
        return $"({a} / {safeB})";
    }

    private string BuildUnaryAuto(ShaderNode node, string fn)
    {
        var xPin = InputAny(node, "In", "X");
        var type = ResolveInputType(xPin);
        var x = BuildInput(xPin, type);
        return $"{fn}({x})";
    }

    private string BuildLength(ShaderNode node)
    {
        var vectorPin = InputAny(node, "In", "Vector");
        var type = ResolveInputType(vectorPin);
        if (type == PinType.Float)
            return $"abs({BuildInput(vectorPin, PinType.Float)})";
        var vecType = type == PinType.Vec2 ? PinType.Vec2 : PinType.Vec3;
        return $"length({BuildInput(vectorPin, vecType)})";
    }

    private string BuildNormalize(ShaderNode node)
    {
        var vectorPin = InputAny(node, "In", "Vector");
        var type = ResolveInputType(vectorPin);
        var vecType = type == PinType.Vec2 ? PinType.Vec2 : PinType.Vec3;
        return $"normalize({BuildInput(vectorPin, vecType)})";
    }

    private string BuildDot(ShaderNode node)
    {
        var aPin = node.Input("A")!;
        var bPin = node.Input("B")!;
        var type = HighestNumericType(ResolveInputType(aPin), ResolveInputType(bPin));
        var vecType = type == PinType.Vec2 ? PinType.Vec2 : PinType.Vec3;
        return $"dot({BuildInput(aPin, vecType)}, {BuildInput(bPin, vecType)})";
    }

    private string BuildDistance(ShaderNode node)
    {
        var aPin = node.Input("A")!;
        var bPin = node.Input("B")!;
        var type = HighestNumericType(ResolveInputType(aPin), ResolveInputType(bPin));
        var vecType = type == PinType.Vec2 ? PinType.Vec2 : PinType.Vec3;
        return $"distance({BuildInput(aPin, vecType)}, {BuildInput(bPin, vecType)})";
    }

    private string BuildOneMinus(ShaderNode node)
    {
        var xPin = InputAny(node, "In", "X");
        var type = ResolveInputType(xPin);
        var x = BuildInput(xPin, type);
        return $"({ConstructorForType(type, "1.0")} - {x})";
    }

    private string BuildNegate(ShaderNode node)
    {
        var xPin = InputAny(node, "In", "X");
        var type = ResolveInputType(xPin);
        return $"(-{BuildInput(xPin, type)})";
    }

    private string BuildReciprocal(ShaderNode node)
    {
        var xPin = InputAny(node, "In", "X");
        var type = ResolveInputType(xPin);
        var x = BuildInput(xPin, type);
        var safe = type == PinType.Float
            ? $"max(abs({x}), 0.00001)"
            : $"max(abs({x}), {ConstructorForType(type, "0.00001")})";
        return $"({ConstructorForType(type, "1.0")} / {safe})";
    }

    private string BuildMultiplyAdd(ShaderNode node)
    {
        var aPin = node.Input("A")!;
        var bPin = node.Input("B")!;
        var cPin = node.Input("C")!;
        var type = HighestNumericType(HighestNumericType(ResolveInputType(aPin), ResolveInputType(bPin)), ResolveInputType(cPin));
        var a = BuildInput(aPin, type);
        var b = BuildInput(bPin, type);
        var c = BuildInput(cPin, type);
        return $"(({a} * {b}) + {c})";
    }

    private string BuildSaturate(ShaderNode node)
    {
        var xPin = InputAny(node, "In", "X");
        var type = ResolveInputType(xPin);
        var x = BuildInput(xPin, type);
        return $"clamp({x}, {ConstructorForType(type, "0.0")}, {ConstructorForType(type, "1.0")})";
    }

    private string BuildStep(ShaderNode node)
    {
        var edgePin = node.Input("Edge")!;
        var xPin = InputAny(node, "In", "X");
        var type = HighestNumericType(ResolveInputType(edgePin), ResolveInputType(xPin));
        var edge = BuildInput(edgePin, type);
        var x = BuildInput(xPin, type);
        return $"step({edge}, {x})";
    }

    private string BuildMinMax(ShaderNode node, GraphPin outputPin, string fn)
    {
        var aPin = node.Input("A")!;
        var bPin = node.Input("B")!;
        var type = HighestNumericType(ResolveInputType(aPin), ResolveInputType(bPin), outputPin.Type);
        var a = BuildInput(aPin, type);
        var b = BuildInput(bPin, type);
        return $"{fn}({a}, {b})";
    }

    private string BuildLerp(ShaderNode node, GraphPin outputPin)
    {
        var aPin = node.Input("A")!;
        var bPin = node.Input("B")!;
        var type = HighestNumericType(ResolveInputType(aPin), ResolveInputType(bPin), outputPin.Type);
        var a = BuildInput(aPin, type);
        var b = BuildInput(bPin, type);
        var t = BuildInput(node.Input("T")!, PinType.Float);
        return $"mix({a}, {b}, clamp({t}, 0.0, 1.0))";
    }

    private PinType ResolveInputType(GraphPin? inputPin)
    {
        if (inputPin is null)
            return PinType.Float;

        var connection = _graph.FindConnectionToInput(inputPin.Id);
        if (connection is null)
            return inputPin.Type;

        var sourcePin = _graph.FindPin(connection.FromPinId);
        var sourceNode = _graph.FindNodeByPin(connection.FromPinId);
        if (sourcePin is null || sourceNode is null)
            return inputPin.Type;

        return ResolveOutputType(sourceNode, sourcePin);
    }

    private PinType ResolveOutputType(ShaderNode sourceNode, GraphPin sourcePin)
    {
        if (sourceNode.Kind is NodeKind.Add or NodeKind.Subtract or NodeKind.Multiply or NodeKind.Divide or NodeKind.Min or NodeKind.Max or NodeKind.Lerp)
        {
            var a = sourceNode.Input("A");
            var b = sourceNode.Input("B");
            if (a is not null && b is not null)
                return HighestNumericType(ResolveInputType(a), ResolveInputType(b), sourcePin.Type);
        }

        if (sourceNode.Kind == NodeKind.MultiplyAdd)
        {
            var a = sourceNode.Input("A");
            var b = sourceNode.Input("B");
            var c = sourceNode.Input("C");
            if (a is not null && b is not null && c is not null)
                return HighestNumericType(ResolveInputType(a), ResolveInputType(b), ResolveInputType(c), sourcePin.Type);
        }

        if (sourceNode.Kind is NodeKind.Sin or NodeKind.Cos or NodeKind.OneMinus or NodeKind.Saturate
            or NodeKind.Step or NodeKind.Abs or NodeKind.Floor or NodeKind.Ceil or NodeKind.Fraction
            or NodeKind.Negate or NodeKind.Reciprocal)
        {
            var x = InputAny(sourceNode, "In", "X");
            if (x is not null)
                return HighestNumericType(ResolveInputType(x), sourcePin.Type);
        }

        if (sourceNode.Kind == NodeKind.Mix)
        {
            var a = sourceNode.Input("A");
            var b = sourceNode.Input("B");
            if (a is not null && b is not null)
                return HighestNumericType(ResolveInputType(a), ResolveInputType(b), PinType.Vec3);
        }

        if (sourceNode.Kind == NodeKind.SubGraph)
        {
            var input = sourcePin.Type switch
            {
                PinType.Float => sourceNode.Input("Float In") ?? sourceNode.Input("In"),
                PinType.Vec2 => sourceNode.Input("Vec2 In") ?? sourceNode.Input("In"),
                PinType.Vec4 => sourceNode.Input("Vec4 In") ?? sourceNode.Input("In"),
                _ => sourceNode.Input("Vec3 In") ?? sourceNode.Input("In")
            };
            if (input is not null)
                return HighestNumericType(ResolveInputType(input), sourcePin.Type);
        }

        return sourcePin.Type;
    }

    private static PinType HighestNumericType(params PinType[] types)
    {
        var rank = types.Select(t => t switch
        {
            PinType.Vec4 => 4,
            PinType.Vec3 => 3,
            PinType.Vec2 => 2,
            _ => 1
        }).Max();

        return rank switch
        {
            4 => PinType.Vec4,
            3 => PinType.Vec3,
            2 => PinType.Vec2,
            _ => PinType.Float
        };
    }

    private static int ComponentCount(PinType type) => type switch
    {
        PinType.Vec4 => 4,
        PinType.Vec3 => 3,
        PinType.Vec2 => 2,
        _ => 1
    };

    private static string ConstructorForType(PinType type, string scalar) => type switch
    {
        PinType.Vec2 => $"vec2({scalar})",
        PinType.Vec3 => $"vec3({scalar})",
        PinType.Vec4 => $"vec4({scalar})",
        _ => scalar
    };

    private string BuildPower(ShaderNode node)
    {
        var x = BuildInput(InputAny(node, "A", "X"), PinType.Float);
        var p = BuildInput(InputAny(node, "B", "Power"), PinType.Float);
        return $"pow(max({x}, 0.0), {p})";
    }

    private string BuildClamp(ShaderNode node)
    {
        var x = BuildInput(InputAny(node, "In", "X"), PinType.Float);
        var min = BuildInput(node.Input("Min")!, PinType.Float);
        var max = BuildInput(node.Input("Max")!, PinType.Float);
        return $"clamp({x}, {min}, {max})";
    }

    private string BuildSmoothstep(ShaderNode node)
    {
        var a = BuildInput(InputAny(node, "Edge1", "Edge A"), PinType.Float);
        var b = BuildInput(InputAny(node, "Edge2", "Edge B"), PinType.Float);
        var x = BuildInput(InputAny(node, "In", "X"), PinType.Float);
        return $"smoothstep({a}, {b}, {x})";
    }

    private string BuildRemap(ShaderNode node)
    {
        var inputPin = node.Input("In") ?? node.Input("X");
        var inRangePin = node.Input("In Min Max") ?? node.Input("From Min") ?? node.Input("From Max");
        var outRangePin = node.Input("Out Min Max") ?? node.Input("To Min") ?? node.Input("To Max");

        var input = BuildInput(inputPin, PinType.Float);
        var inRange = BuildInput(inRangePin, PinType.Vec2);
        var outRange = BuildInput(outRangePin, PinType.Vec2);

        return $"mix(({outRange}).x, ({outRange}).y, clamp(({input} - ({inRange}).x) / max(abs(({inRange}).y - ({inRange}).x), 0.00001), 0.0, 1.0))";
    }

    private string BuildPosterize(ShaderNode node)
    {
        var x = BuildInput(InputAny(node, "In", "X"), PinType.Float);
        var steps = BuildInput(node.Input("Steps")!, PinType.Float);
        return $"(floor({x} * max({steps}, 1.0)) / max({steps}, 1.0))";
    }

    private string BuildNoise(ShaderNode node)
    {
        _features.Add("noise");
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var scale = BuildInput(node.Input("Scale")!, PinType.Float);
        return $"noise({uv} * {scale})";
    }

    private string BuildVoronoi(ShaderNode node, GraphPin outputPin)
    {
        _features.Add("voronoi");
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var densityPin = InputAny(node, "Cell Density", "CellDensity", "Scale");
        var density = densityPin is null ? "5.0" : BuildInput(densityPin, PinType.Float);
        var anglePin = InputAny(node, "Angle Offset", "AngleOffset");
        var angleOffset = anglePin is null ? "2.0" : BuildInput(anglePin, PinType.Float);
        return outputPin.Name.Equals("Cells", StringComparison.OrdinalIgnoreCase)
            ? $"voronoiCells({uv} * {density}, {angleOffset})"
            : $"voronoi({uv} * {density}, {angleOffset})";
    }

    private string BuildGradientNoise(ShaderNode node)
    {
        _features.Add("gradientnoise");
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var scale = BuildInput(node.Input("Scale")!, PinType.Float);
        return $"gradientNoise({uv} * {scale})";
    }

    private string BuildCheckerboard(ShaderNode node)
    {
        _features.Add("checkerboard");
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var frequency = BuildInput(node.Input("Frequency")!, PinType.Vec2);
        return $"checkerboard({uv}, {frequency})";
    }

    private string BuildSceneDepth(ShaderNode node, GraphPin outputPin)
    {
        _features.Add("scenedepth");
        var uvPin = node.Input("UV");
        var uvType = ResolveInputType(uvPin);
        var screenPosition = uvType == PinType.Vec4
            ? (IsInputConnectedFrom(uvPin, NodeKind.ScreenPosition) ? "v_ScreenPos" : BuildInput(uvPin, PinType.Vec4))
            : string.Empty;
        var uv = uvType == PinType.Vec4
            ? $"((({screenPosition}).xy / max(({screenPosition}).w, 0.00001)) * 0.5 + 0.5)"
            : BuildInput(uvPin, PinType.Vec2);
        var raw = $"texture(u_SceneDepth, {uv}).r";

        var mode = string.IsNullOrWhiteSpace(node.TextValue) ? "Eye" : node.TextValue.Trim();
        return mode.ToLowerInvariant() switch
        {
            "eye" => $"sceneDepthLinearEye({raw})",
            "raw" => raw,
            "linear01" => $"sceneDepthLinear01({raw})",
            _ => raw
        };
    }

    private string BuildDepthFade(ShaderNode node)
    {
        _features.Add("scenedepth");
        var distance = BuildInput(node.Input("Distance")!, PinType.Float);
        const string screenUv = "((v_ScreenPos.xy / max(v_ScreenPos.w, 0.00001)) * 0.5 + 0.5)";
        return $"depthFade({screenUv}, {distance}, v_FragDepth)";
    }

    private string BuildTriplanar(ShaderNode node, GraphPin outputPin)
    {
        _features.Add("triplanar");
        var texturePin = node.Input("Texture");
        var samplerName = texturePin is null ? SanitizeIdentifier(TextureUniformName(node)) : BuildInput(texturePin, PinType.Texture2D);
        samplerName = SanitizeIdentifier(samplerName);
        var scale = BuildInput(node.Input("Scale")!, PinType.Float);
        var blend = BuildInput(node.Input("Blend")!, PinType.Float);
        var sample = $"triplanar({samplerName}, v_WorldPos, normalize(v_NormalWS), {scale}, {blend})";

        return outputPin.Name.ToLowerInvariant() switch
        {
            "r" => $"{sample}.r",
            "g" => $"{sample}.g",
            "b" => $"{sample}.b",
            _ => sample
        };
    }

    private string BuildFresnel(ShaderNode node)
    {
        var normal = BuildInput(node.Input("Normal")!, PinType.Vec3);
        var power = BuildInput(node.Input("Power")!, PinType.Float);
        return $"pow(1.0 - clamp(dot(normalize({normal}), normalize(u_CameraPos - v_WorldPos)), 0.0, 1.0), {power})";
    }

    private string BuildFresnelPro(ShaderNode node)
    {
        var normal = BuildInput(node.Input("Normal")!, PinType.Vec3);
        var viewDir = BuildInput(node.Input("View Dir")!, PinType.Vec3);
        var power = BuildInput(node.Input("Power")!, PinType.Float);
        var bias = BuildInput(node.Input("Bias")!, PinType.Float);
        var scale = BuildInput(node.Input("Scale")!, PinType.Float);
        return $"clamp(({bias}) + ({scale}) * pow(1.0 - clamp(dot(normalize({normal}), normalize({viewDir})), 0.0, 1.0), {power}), 0.0, 8.0)";
    }

    private string BuildRimLight(ShaderNode node, GraphPin outputPin)
    {
        var normal = BuildInput(node.Input("Normal")!, PinType.Vec3);
        var power = BuildInput(node.Input("Power")!, PinType.Float);
        var intensity = BuildInput(node.Input("Intensity")!, PinType.Float);
        var mask = $"pow(1.0 - clamp(dot(normalize({normal}), normalize(u_CameraPos - v_WorldPos)), 0.0, 1.0), {power}) * {intensity}";
        if (outputPin.Name.Equals("Mask", StringComparison.OrdinalIgnoreCase))
            return mask;

        return $"({ToVec3(node.ColorHex, node.ColorIntensity)} * {mask})";
    }

    private string BuildEmissionPulse(ShaderNode node, GraphPin outputPin)
    {
        var color = BuildInput(node.Input("Color")!, PinType.Vec3);
        var intensityPin = node.Input("Intensity") ?? node.Input("Pulse") ?? node.Input("Max");
        var intensity = intensityPin is null ? "1.0" : BuildInput(intensityPin, PinType.Float);
        if (outputPin.Name.Equals("Intensity", StringComparison.OrdinalIgnoreCase) ||
            outputPin.Name.Equals("Pulse", StringComparison.OrdinalIgnoreCase))
            return intensity;

        return $"({color} * {intensity})";
    }

    private string BuildDissolve(ShaderNode node, GraphPin outputPin)
    {
        _features.Add("dissolve");
        var mask = BuildInput(node.Input("Mask")!, PinType.Float);
        var amount = BuildInput(node.Input("Amount")!, PinType.Float);
        var edgeWidth = BuildInput(node.Input("Edge Width")!, PinType.Float);
        return outputPin.Name.Equals("Edge", StringComparison.OrdinalIgnoreCase)
            ? $"dissolveEdge({mask}, {amount}, {edgeWidth})"
            : $"dissolveAlpha({mask}, {amount}, {edgeWidth})";
    }

    private string BuildSubGraph(ShaderNode node, GraphPin outputPin)
    {
        var assetName = string.IsNullOrWhiteSpace(node.TextValue) ? node.Title : node.TextValue.Trim();
        var asset = _graph.SubGraphs.FirstOrDefault(s =>
            s.Name.Equals(assetName, StringComparison.OrdinalIgnoreCase) ||
            s.Id.ToString().Equals(assetName, StringComparison.OrdinalIgnoreCase));

        if (asset is not null && asset.Nodes.Count > 0)
        {
            // Inline real del sub-grafo guardado: se evalúa el Master Output interno y se
            // inserta su expresión en el shader principal. Como este generador es expresional,
            // no genera variables temporales que puedan colisionar. Los SubGraph inputs externos
            // caen al passthrough seguro de abajo si el asset todavía no define salida completa.
            var previousGraph = _graph;
            try
            {
                var subGraphModel = new ShaderGraphModel
                {
                    Name = asset.Name,
                    Nodes = asset.Nodes,
                    Connections = asset.Connections,
                    Properties = previousGraph.Properties,
                    SubGraphs = previousGraph.SubGraphs
                };
                _graph = subGraphModel;
                var output = subGraphModel.Nodes.FirstOrDefault(n => n.Kind == NodeKind.Output);
                if (output is not null)
                {
                    var pinName = outputPin.Type switch
                    {
                        PinType.Float => "Alpha",
                        PinType.Vec2 => "UV",
                        PinType.Vec4 => "RGBA",
                        _ => "Base Color"
                    };
                    return BuildOutputInput(output, pinName, outputPin.Type, DefaultForType(outputPin.Type));
                }
            }
            finally
            {
                _graph = previousGraph;
            }
        }

        // Passthrough seguro para subgraphs vacíos o en construcción.
        var input = outputPin.Type switch
        {
            PinType.Float => node.Input("Float In") ?? node.Input("In"),
            PinType.Vec2 => node.Input("Vec2 In") ?? node.Input("In"),
            PinType.Vec4 => node.Input("Vec4 In") ?? node.Input("In"),
            _ => node.Input("Vec3 In") ?? node.Input("In")
        };
        if (input is null)
            return DefaultForType(outputPin.Type);

        var type = HighestNumericType(ResolveInputType(input), outputPin.Type);
        return CastExpression(BuildInput(input, type), type, outputPin.Type);
    }

    private string BuildGradient(ShaderNode node)
    {
        var t = BuildInput(node.Input("T")!, PinType.Float);
        return $"mix({ToVec3(node.ColorHex, node.ColorIntensity)}, {ToVec3(node.ColorHex2, node.ColorIntensity2)}, clamp({t}, 0.0, 1.0))";
    }


    private string BuildTwirl(ShaderNode node)
    {
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var strength = BuildInput(node.Input("Strength")!, PinType.Float);
        var center = BuildInput(node.Input("Center")!, PinType.Vec2);
        return $"twirlUV({uv}, {center}, {strength})";
    }

    private string BuildNormalMap(ShaderNode node)
    {
        var texturePin = node.Input("Texture");
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var strength = BuildInput(node.Input("Strength")!, PinType.Float);
        var samplerName = texturePin is null ? SanitizeIdentifier(TextureUniformName(node)) : BuildInput(texturePin, PinType.Texture2D);
        samplerName = SanitizeIdentifier(samplerName);
        _features.Add("normalmap");
        return $"applyNormalMap(normalize(v_NormalWS), normalize(v_TangentWS), texture({samplerName}, {uv}).xyz, clamp({strength}, 0.0, 8.0))";
    }

    private string BuildNormalStrength(ShaderNode node)
    {
        var normal = BuildInput(node.Input("Normal")!, PinType.Vec3);
        var strength = BuildInput(node.Input("Strength")!, PinType.Float);
        return $"normalize(vec3(({normal}).xy * {strength}, ({normal}).z))";
    }

    private string BuildNormalBlend(ShaderNode node)
    {
        var a = BuildInput(node.Input("A")!, PinType.Vec3);
        var b = BuildInput(node.Input("B")!, PinType.Vec3);
        var strength = BuildInput(node.Input("Strength")!, PinType.Float);
        return $"normalize(vec3(({a}).xy + ({b}).xy * {strength}, ({a}).z * ({b}).z))";
    }

    private string BuildScalarTextureMap(ShaderNode node)
    {
        var texturePin = node.Input("Texture");
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var strength = BuildInput(node.Input("Strength")!, PinType.Float);
        var samplerName = texturePin is null ? SanitizeIdentifier(TextureUniformName(node)) : BuildInput(texturePin, PinType.Texture2D);
        samplerName = SanitizeIdentifier(samplerName);
        return $"clamp(texture({samplerName}, {uv}).r * {strength}, 0.0, 1.0)";
    }

    private string BuildChannelSplit(ShaderNode node, GraphPin outputPin)
    {
        var input = node.Input("In");
        var inputType = ResolveInputType(input);
        var componentCount = ComponentCount(inputType);
        var value = BuildInput(input, inputType);
        return outputPin.Name.ToUpperInvariant() switch
        {
            "G" => componentCount >= 2 ? $"({value}).g" : "0.0",
            "B" => componentCount >= 3 ? $"({value}).b" : "0.0",
            "A" => componentCount >= 4 ? $"({value}).a" : "0.0",
            _ => inputType == PinType.Float ? value : $"({value}).r"
        };
    }

    private string BuildChannelCombine(ShaderNode node, GraphPin outputPin)
    {
        var r = BuildInput(node.Input("R")!, PinType.Float);
        var g = BuildInput(node.Input("G")!, PinType.Float);
        var b = BuildInput(node.Input("B")!, PinType.Float);
        var a = BuildInput(node.Input("A")!, PinType.Float);
        var rgba = $"vec4({r}, {g}, {b}, {a})";
        return outputPin.Name.Equals("RGB", StringComparison.OrdinalIgnoreCase) ? $"({rgba}).rgb" : rgba;
    }

    private string BuildSwizzle(ShaderNode node, GraphPin outputPin)
    {
        var input = BuildInput(node.Input("In")!, PinType.Vec4);
        var raw = (node.TextValue ?? "rgba").Trim().ToLowerInvariant();

        // Normaliza xyzw -> rgba para evitar swizzles mixtos inválidos en GLSL (p.ej. ".rxyz").
        var xyzwToRgba = new Dictionary<char, char> { ['x'] = 'r', ['y'] = 'g', ['z'] = 'b', ['w'] = 'a' };
        var pattern = new string(raw
            .Where(c => "rgbaxyzw".Contains(c))
            .Select(c => xyzwToRgba.TryGetValue(c, out var mapped) ? mapped : c)
            .ToArray());
        if (string.IsNullOrEmpty(pattern))
            pattern = "rgba";

        if (outputPin.Name.Equals("X", StringComparison.OrdinalIgnoreCase))
            return $"({input}).{pattern[0]}";
        if (outputPin.Name.Equals("RGB", StringComparison.OrdinalIgnoreCase))
        {
            if (pattern.Length >= 3)
                return $"({input}).{pattern[..3]}";

            // Patrón corto (1-2 canales): respeta el swizzle pedido y rellena el resto con 0.0.
            var rgbDefaults = new[] { "0.0", "0.0" };
            var rgbList = pattern.Select(c => $"({input}).{c}").Concat(rgbDefaults).Take(3);
            return $"vec3({string.Join(", ", rgbList)})";
        }
        if (pattern.Length >= 4)
            return $"({input}).{pattern[..4]}";

        // Constructor vec4 con el número correcto de componentes (rellena con 0.0 / alpha 1.0).
        var defaults = new[] { "0.0", "0.0", "0.0", "1.0" };
        var components = pattern.Select(c => $"({input}).{c}").Concat(defaults.Skip(pattern.Length)).Take(4);
        return $"vec4({string.Join(", ", components)})";
    }

    private string BuildAppend(ShaderNode node, GraphPin outputPin)
    {
        var aPin = node.Input("A")!;
        var aType = ResolveInputType(aPin);
        var b = BuildInput(node.Input("B")!, PinType.Float);
        var wantsVec3 = outputPin.Name.Equals("Vec3", StringComparison.OrdinalIgnoreCase);

        switch (aType)
        {
            case PinType.Vec2:
            {
                var a2 = BuildInput(aPin, PinType.Vec2);
                return wantsVec3 ? $"vec3({a2}, {b})" : $"vec4({a2}, {b}, 1.0)";
            }
            case PinType.Float:
            {
                var a1 = BuildInput(aPin, PinType.Float);
                return wantsVec3 ? $"vec3({a1}, {b}, 0.0)" : $"vec4({a1}, {b}, 0.0, 1.0)";
            }
            default:
            {
                var a3 = BuildInput(aPin, PinType.Vec3);
                return wantsVec3 ? a3 : $"vec4({a3}, {b})";
            }
        }
    }

    private string BuildChannelMask(ShaderNode node)
    {
        var c = BuildInput(node.Input("Color")!, PinType.Vec3);
        var channel = (node.TextValue ?? "R").Trim().ToUpperInvariant();
        return channel switch
        {
            "G" => $"({c}).g",
            "B" => $"({c}).b",
            "A" => "1.0",
            "LUMA" or "LUMINANCE" or "GRAY" or "GRAYSCALE" => $"dot({c}, vec3(0.2126, 0.7152, 0.0722))",
            _ => $"({c}).r"
        };
    }

    private string BuildBrightnessContrast(ShaderNode node)
    {
        var c = BuildInput(node.Input("Color")!, PinType.Vec3);
        var brightness = BuildInput(node.Input("Brightness")!, PinType.Float);
        var contrast = BuildInput(node.Input("Contrast")!, PinType.Float);
        return $"clamp((({c} - vec3(0.5)) * {contrast}) + vec3(0.5 + {brightness}), vec3(0.0), vec3(64.0))";
    }

    private string BuildColorRamp(ShaderNode node)
    {
        var t = BuildInput(node.Input("T")!, PinType.Float);
        var contrast = BuildInput(node.Input("Contrast")!, PinType.Float);
        return $"mix({ToVec3(node.ColorHex, node.ColorIntensity)}, {ToVec3(node.ColorHex2, node.ColorIntensity2)}, clamp((({t} - 0.5) * {contrast}) + 0.5, 0.0, 1.0))";
    }

    private string BuildPolarCoordinates(ShaderNode node)
    {
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var center = BuildInput(node.Input("Center")!, PinType.Vec2);
        var radial = BuildInput(node.Input("Radial Scale")!, PinType.Float);
        var angular = BuildInput(node.Input("Angular Scale")!, PinType.Float);
        return $"polarUV({uv}, {center}, {radial}, {angular})";
    }

    private string BuildRadialGradient(ShaderNode node)
    {
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var center = BuildInput(node.Input("Center")!, PinType.Vec2);
        var radius = BuildInput(node.Input("Radius")!, PinType.Float);
        var softness = BuildInput(node.Input("Softness")!, PinType.Float);
        return $"(1.0 - smoothstep(max({radius} - {softness}, 0.0), {radius}, distance({uv}, {center})))";
    }

    private string BuildSphereMask(ShaderNode node)
    {
        var pos = BuildInput(node.Input("Position")!, PinType.Vec3);
        var center = BuildInput(node.Input("Center")!, PinType.Vec3);
        var radius = BuildInput(node.Input("Radius")!, PinType.Float);
        var softness = BuildInput(node.Input("Softness")!, PinType.Float);
        return $"(1.0 - smoothstep(max({radius} - {softness}, 0.0), {radius}, distance({pos}, {center})))";
    }

    private string BuildBlend(ShaderNode node)
    {
        var a = BuildInput(node.Input("A")!, PinType.Vec3);
        var b = BuildInput(node.Input("B")!, PinType.Vec3);
        var opacity = BuildInput(node.Input("Opacity")!, PinType.Float);
        var mode = (node.TextValue ?? "Add").Trim().ToUpperInvariant();
        var blended = mode switch
        {
            "MULTIPLY" => $"({a} * {b})",
            "SCREEN" => $"(vec3(1.0) - (vec3(1.0) - {a}) * (vec3(1.0) - {b}))",
            "OVERLAY" => $"blendOverlay({a}, {b})",
            "ALPHA" or "LERP" or "MIX" => $"mix({a}, {b}, clamp({opacity}, 0.0, 1.0))",
            _ => $"({a} + {b})"
        };
        return mode is "ALPHA" or "LERP" or "MIX" ? blended : $"mix({a}, {blended}, clamp({opacity}, 0.0, 1.0))";
    }

    private string BuildPanner(ShaderNode node)
    {
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var speedPin = node.Input("Speed");
        var speed = speedPin is null ? "vec2(0.1, 0.0)" : BuildInput(speedPin, PinType.Vec2);
        var timePin = node.Input("Time");
        var time = timePin is null ? "0.0" : BuildInput(timePin, PinType.Float);
        return $"({uv} + {speed} * {time})";
    }

    private string BuildTilingOffset(ShaderNode node)
    {
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var tiling = BuildInput(node.Input("Tiling")!, PinType.Vec2);
        var offset = BuildInput(node.Input("Offset")!, PinType.Vec2);
        return $"({uv} * {tiling} + {offset})";
    }

    private string BuildRotator(ShaderNode node)
    {
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var angle = BuildInput(node.Input("Angle")!, PinType.Float);
        if (string.Equals(node.TextValue, "Degrees", StringComparison.OrdinalIgnoreCase))
            angle = $"radians({angle})";
        return $"rotateUV({uv}, {angle})";
    }

    private string BuildParallaxOffset(ShaderNode node)
    {
        var uv = BuildInput(node.Input("UV")!, PinType.Vec2);
        var height = BuildInput(node.Input("Height")!, PinType.Float);
        var scale = BuildInput(node.Input("Scale")!, PinType.Float);
        var viewDir = BuildInput(node.Input("View Dir")!, PinType.Vec3);
        return $"({uv} + normalize({viewDir}).xy * (({height} - 0.5) * {scale}))";
    }

    private string BuildMix(ShaderNode node)
    {
        var a = BuildInput(node.Input("A")!, PinType.Vec3);
        var b = BuildInput(node.Input("B")!, PinType.Vec3);
        var t = BuildInput(node.Input("T")!, PinType.Float);
        return $"mix({a}, {b}, clamp({t}, 0.0, 1.0))";
    }

    private static string CastExpression(string expr, PinType from, PinType to)
    {
        expr = NormalizeDefaultExpression(expr, from);
        if (from == to)
            return expr;

        return (from, to) switch
        {
            (PinType.Float, PinType.Vec2) => $"vec2({expr})",
            (PinType.Float, PinType.Vec3) => $"vec3({expr})",
            (PinType.Float, PinType.Vec4) => $"vec4(vec3({expr}), 1.0)",
            (PinType.Vec2, PinType.Float) => $"({expr}).x",
            (PinType.Vec2, PinType.Vec3) => $"vec3({expr}, 0.0)",
            (PinType.Vec2, PinType.Vec4) => $"vec4({expr}, 0.0, 1.0)",
            (PinType.Vec3, PinType.Float) => $"dot({expr}, vec3(0.2126, 0.7152, 0.0722))",
            (PinType.Vec3, PinType.Vec2) => $"({expr}).xy",
            (PinType.Vec3, PinType.Vec4) => $"vec4({expr}, 1.0)",
            (PinType.Vec4, PinType.Float) => $"({expr}).x",
            (PinType.Vec4, PinType.Vec2) => $"({expr}).xy",
            (PinType.Vec4, PinType.Vec3) => $"({expr}).rgb",
            _ => expr
        };
    }

    private static string NormalizeDefaultExpression(string expr, PinType type)
    {
        expr = string.IsNullOrWhiteSpace(expr) ? DefaultForType(type) : expr.Trim();
        if (expr.Equals("v_UV", StringComparison.OrdinalIgnoreCase))
            return "v_UV";
        if (expr.Equals("v_UV.x", StringComparison.OrdinalIgnoreCase))
            return "v_UV.x";
        if (expr.Equals("v_UV.y", StringComparison.OrdinalIgnoreCase))
            return "v_UV.y";
        return expr;
    }

    private static string DefaultForType(PinType type) => type switch
    {
        PinType.Float => "0.0",
        PinType.Vec2 => "vec2(0.0)",
        PinType.Vec3 => "vec3(0.0)",
        PinType.Vec4 => "vec4(0.0)",
        PinType.Texture2D => "u_MainTex",
        _ => "0.0"
    };

    private static string ToVec3(string colorHex, float intensity = 1f)
    {
        intensity = NormalizeHdrIntensity(intensity);

        try
        {
            var parsed = MediaColorConverter.ConvertFromString(colorHex);
            if (parsed is MediaColor c)
            {
                var r = c.R / 255f * intensity;
                var g = c.G / 255f * intensity;
                var b = c.B / 255f * intensity;
                return $"vec3({F(r)}, {F(g)}, {F(b)})";
            }
        }
        catch
        {
            // Use magenta when the color is invalid.
        }

        return $"vec3({F(intensity)}, 0.0, {F(intensity)})";
    }

    private static float NormalizeHdrIntensity(float intensity)
    {
        if (float.IsNaN(intensity) || float.IsInfinity(intensity) || intensity <= 0f)
            return 1f;

        return Math.Clamp(intensity, 0.05f, 64f);
    }

    private static string ToVec2(string text)
    {
        var values = ParseFloats(text, 2);
        return $"vec2({F(values[0])}, {F(values[1])})";
    }

    private static string ToVec3FromText(string text)
    {
        var values = ParseFloats(text, 3);
        return $"vec3({F(values[0])}, {F(values[1])}, {F(values[2])})";
    }

    private static float[] ParseFloats(string text, int count)
    {
        var result = Enumerable.Repeat(0f, count).ToArray();
        if (string.IsNullOrWhiteSpace(text))
            return result;

        var clean = text.Replace("vec2", string.Empty, StringComparison.OrdinalIgnoreCase)
                        .Replace("vec3", string.Empty, StringComparison.OrdinalIgnoreCase)
                        .Replace("(", string.Empty)
                        .Replace(")", string.Empty);
        var parts = clean.Split(new[] { ',', ';', ' ' }, StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        for (var i = 0; i < Math.Min(count, parts.Length); i++)
        {
            if (float.TryParse(parts[i], NumberStyles.Float, CultureInfo.InvariantCulture, out var value))
                result[i] = value;
        }
        return result;
    }

    private static string F(float value)
        => value.ToString("0.######", CultureInfo.InvariantCulture);

    private static string ToHlslUniformField(string glslUniformLine)
    {
        var line = glslUniformLine.Trim().TrimEnd(';');
        if (line.StartsWith("uniform ", StringComparison.OrdinalIgnoreCase))
            line = line[8..];

        line = line.Replace("vec2", "float2", StringComparison.Ordinal)
                   .Replace("vec3", "float3", StringComparison.Ordinal)
                   .Replace("vec4", "float4", StringComparison.Ordinal);

        return line + ";";
    }

    private static string ToHlslExpression(string expr)
    {
        expr = expr.Replace("vec2", "float2", StringComparison.Ordinal)
                   .Replace("vec3", "float3", StringComparison.Ordinal)
                   .Replace("vec4", "float4", StringComparison.Ordinal)
                   .Replace("mix(", "lerp(", StringComparison.Ordinal)
                   .Replace("fract(", "frac(", StringComparison.Ordinal)
                   .Replace("mod(", "fmod(", StringComparison.Ordinal);

        expr = Regex.Replace(expr, @"texture\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,", "$1.Sample(GrokoLinearSampler, ");
        return expr;
    }

    private void AppendHlslFeatureFunctions(StringBuilder sb)
    {
        sb.AppendLine("float3 fresnelSchlick(float cosTheta, float3 F0) { return F0 + (1.0 - F0) * pow(1.0 - saturate(cosTheta), 5.0); }");
        sb.AppendLine("float DistributionGGX(float3 N, float3 H, float roughness) { float a = roughness * roughness; float a2 = a * a; float NdotH = saturate(dot(N, H)); float NdotH2 = NdotH * NdotH; float denom = (NdotH2 * (a2 - 1.0) + 1.0); return a2 / max(3.14159265 * denom * denom, 0.0001); }");
        sb.AppendLine("float GeometrySchlickGGX(float NdotV, float roughness) { float r = roughness + 1.0; float k = (r * r) / 8.0; return NdotV / max(NdotV * (1.0 - k) + k, 0.0001); }");
        sb.AppendLine("float GeometrySmith(float3 N, float3 V, float3 L, float roughness) { float ggx2 = GeometrySchlickGGX(saturate(dot(N, V)), roughness); float ggx1 = GeometrySchlickGGX(saturate(dot(N, L)), roughness); return ggx1 * ggx2; }");
        sb.AppendLine("float3 applyNormalMap(float3 normalWS, float3 tangentWS, float3 sampleRGB, float strength) { float3 n = normalize(normalWS); float3 t = normalize(tangentWS - n * dot(tangentWS, n)); if (length(t) < 0.001) t = normalize(abs(n.y) > 0.99 ? float3(1.0, 0.0, 0.0) : cross(float3(0.0, 1.0, 0.0), n)); float3 b = normalize(cross(n, t)); float3x3 TBN = float3x3(t, b, n); float3 tsn = normalize(sampleRGB * 2.0 - 1.0); tsn.xy *= strength; return normalize(mul(tsn, TBN)); }");
        if (_features.Contains("noise") || _features.Contains("voronoi") || _features.Contains("gradientnoise"))
        {
            sb.AppendLine("float hash(float2 p) { p = frac(p * float2(123.34, 456.21)); p += dot(p, p + 45.32); return frac(p.x * p.y); }");
            sb.AppendLine("float2 hash2(float2 p) { return frac(sin(float2(dot(p, float2(127.1, 311.7)), dot(p, float2(269.5, 183.3)))) * 43758.5453); }");
            sb.AppendLine();
        }

        if (_features.Contains("gradientnoise"))
        {
            sb.AppendLine("float gradientNoise(float2 p)");
            sb.AppendLine("{");
            sb.AppendLine("    float2 i = floor(p);");
            sb.AppendLine("    float2 f = frac(p);");
            sb.AppendLine("    float2 u = f * f * (3.0 - 2.0 * f);");
            sb.AppendLine("    float2 ga = hash2(i) * 2.0 - 1.0;");
            sb.AppendLine("    float2 gb = hash2(i + float2(1.0, 0.0)) * 2.0 - 1.0;");
            sb.AppendLine("    float2 gc = hash2(i + float2(0.0, 1.0)) * 2.0 - 1.0;");
            sb.AppendLine("    float2 gd = hash2(i + float2(1.0, 1.0)) * 2.0 - 1.0;");
            sb.AppendLine("    float va = dot(ga, f - float2(0.0, 0.0));");
            sb.AppendLine("    float vb = dot(gb, f - float2(1.0, 0.0));");
            sb.AppendLine("    float vc = dot(gc, f - float2(0.0, 1.0));");
            sb.AppendLine("    float vd = dot(gd, f - float2(1.0, 1.0));");
            sb.AppendLine("    return 0.5 + lerp(lerp(va, vb, u.x), lerp(vc, vd, u.x), u.y);");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (_features.Contains("checkerboard"))
        {
            sb.AppendLine("float checkerboard(float2 uv, float2 frequency) { float2 c = floor(uv * frequency); return fmod(c.x + c.y, 2.0); }");
            sb.AppendLine();
        }

        if (_features.Contains("scenedepth"))
        {
            sb.AppendLine("float sceneDepthLinearEye(float raw) { float ndcZ = raw * 2.0 - 1.0; return (2.0 * u_CameraNear * u_CameraFar) / (u_CameraFar + u_CameraNear - ndcZ * (u_CameraFar - u_CameraNear)); }");
            sb.AppendLine("float sceneDepthLinear01(float raw) { return (sceneDepthLinearEye(raw) - u_CameraNear) / (u_CameraFar - u_CameraNear); }");
            sb.AppendLine("float depthFade(float2 screenUV, float fadeDistance, float fragDepth) { float sceneEye = sceneDepthLinearEye(u_SceneDepth.Sample(GrokoLinearSampler, screenUV).r); float surfaceEye = sceneDepthLinearEye(fragDepth); return saturate((sceneEye - surfaceEye) / max(fadeDistance, 0.0001)); }");
            sb.AppendLine();
        }

        if (_features.Contains("triplanar"))
        {
            sb.AppendLine("float3 triplanar(Texture2D tex, float3 worldPos, float3 normalWS, float scale, float blendSharpness)");
            sb.AppendLine("{");
            sb.AppendLine("    float3 blend = pow(abs(normalWS), float3(blendSharpness, blendSharpness, blendSharpness));");
            sb.AppendLine("    blend /= max(blend.x + blend.y + blend.z, 0.0001);");
            sb.AppendLine("    float3 x = tex.Sample(GrokoLinearSampler, worldPos.yz * scale).rgb;");
            sb.AppendLine("    float3 y = tex.Sample(GrokoLinearSampler, worldPos.xz * scale).rgb;");
            sb.AppendLine("    float3 z = tex.Sample(GrokoLinearSampler, worldPos.xy * scale).rgb;");
            sb.AppendLine("    return x * blend.x + y * blend.y + z * blend.z;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (_features.Contains("noise"))
        {
            sb.AppendLine("float noise(float2 p)");
            sb.AppendLine("{");
            sb.AppendLine("    float2 i = floor(p);");
            sb.AppendLine("    float2 f = frac(p);");
            sb.AppendLine("    float a = hash(i);");
            sb.AppendLine("    float b = hash(i + float2(1.0, 0.0));");
            sb.AppendLine("    float c = hash(i + float2(0.0, 1.0));");
            sb.AppendLine("    float d = hash(i + float2(1.0, 1.0));");
            sb.AppendLine("    float2 u = f * f * (3.0 - 2.0 * f);");
            sb.AppendLine("    return lerp(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (_features.Contains("voronoi"))
        {
            sb.AppendLine("float voronoi(float2 p, float angleOffset)");
            sb.AppendLine("{");
            sb.AppendLine("    float2 i = floor(p);");
            sb.AppendLine("    float2 f = frac(p);");
            sb.AppendLine("    float minDist = 8.0;");
            sb.AppendLine("    [unroll] for (int y = -1; y <= 1; y++)");
            sb.AppendLine("    {");
            sb.AppendLine("        [unroll] for (int x = -1; x <= 1; x++)");
            sb.AppendLine("        {");
            sb.AppendLine("            float2 neighbor = float2((float)x, (float)y);");
            sb.AppendLine("            float2 point = hash2(i + neighbor);");
            sb.AppendLine("            point = 0.5 + 0.5 * sin(angleOffset + 6.2831 * point);");
            sb.AppendLine("            float2 diff = neighbor + point - f;");
            sb.AppendLine("            minDist = min(minDist, dot(diff, diff));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("    return sqrt(minDist);");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("float voronoiCells(float2 p, float angleOffset)");
            sb.AppendLine("{");
            sb.AppendLine("    float2 i = floor(p);");
            sb.AppendLine("    float2 f = frac(p);");
            sb.AppendLine("    float minDist = 8.0;");
            sb.AppendLine("    float2 minCell = float2(0.0, 0.0);");
            sb.AppendLine("    [unroll] for (int y = -1; y <= 1; y++)");
            sb.AppendLine("    {");
            sb.AppendLine("        [unroll] for (int x = -1; x <= 1; x++)");
            sb.AppendLine("        {");
            sb.AppendLine("            float2 neighbor = float2((float)x, (float)y);");
            sb.AppendLine("            float2 point = hash2(i + neighbor);");
            sb.AppendLine("            point = 0.5 + 0.5 * sin(angleOffset + 6.2831 * point);");
            sb.AppendLine("            float2 diff = neighbor + point - f;");
            sb.AppendLine("            float dist = dot(diff, diff);");
            sb.AppendLine("            if (dist < minDist) { minDist = dist; minCell = i + neighbor; }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("    return hash(minCell);");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (_graph.Nodes.Any(n => n.Kind == NodeKind.Flipbook))
        {
            sb.AppendLine("float2 flipbookUV(float2 uv, float columns, float rows, float frame) { float total = max(columns * rows, 1.0); float f = fmod(floor(frame), total); float x = fmod(f, columns); float y = floor(f / columns); return (uv + float2(x, rows - 1.0 - y)) / float2(columns, rows); }");
            sb.AppendLine();
        }

        if (_graph.Nodes.Any(n => n.Kind == NodeKind.Rotator))
        {
            sb.AppendLine("float2 rotateUV(float2 uv, float angle) { float s = sin(angle); float c = cos(angle); uv -= float2(0.5, 0.5); float2 r = float2(c * uv.x - s * uv.y, s * uv.x + c * uv.y); return r + float2(0.5, 0.5); }");
            sb.AppendLine();
        }

        if (HasOverlayBlend())
        {
            sb.AppendLine("float3 blendOverlay(float3 a, float3 b) { return lerp(2.0 * a * b, 1.0 - 2.0 * (1.0 - a) * (1.0 - b), step(0.5, a)); }");
            sb.AppendLine();
        }

        if (_features.Contains("dissolve"))
        {
            sb.AppendLine("float dissolveAlpha(float mask, float amount, float edgeWidth) { float ew = max(edgeWidth, 0.0001); return smoothstep(amount, amount + ew, mask); }");
            sb.AppendLine("float dissolveEdge(float mask, float amount, float edgeWidth) { float ew = max(edgeWidth, 0.0001); return (1.0 - smoothstep(amount + ew, amount + ew * 2.0, mask)) * smoothstep(amount, amount + ew, mask); }");
            sb.AppendLine();
        }

        if (_graph.Nodes.Any(n => n.Kind == NodeKind.Twirl))
        {
            sb.AppendLine("float2 twirlUV(float2 uv, float2 center, float strength) { float2 delta = uv - center; float dist = length(delta); float angle = strength * (1.0 - smoothstep(0.0, 1.0, dist)); float s = sin(angle); float c = cos(angle); return center + float2(c * delta.x - s * delta.y, s * delta.x + c * delta.y); }");
            sb.AppendLine();
        }

        if (_graph.Nodes.Any(n => n.Kind == NodeKind.PolarCoordinates))
        {
            sb.AppendLine("float2 polarUV(float2 uv, float2 center, float radialScale, float angularScale) { float2 d = uv - center; float r = length(d) * radialScale; float a = atan2(d.y, d.x) / 6.2831853 + 0.5; return float2(r, frac(a * angularScale)); }");
            sb.AppendLine();
        }
    }

    // Recepción de sombras direccionales por cascadas (mismo algoritmo que el shader estándar).

}
